### ISSUE TITLE
按照步骤一步一步的没有运行起来，开始怀疑是libs包没写明其他的引入，后来改了也没用

### ISSUE THREAD

**Issue by hloong** [FacePlusPlus/MegviiFacepp-Android-SDK#24]
手机用的是oppo find5 系统是4.2.2，demo安装成功后直接报错！心累……
错误代码如下：

09-27 14:23:33.997 23103-23103/? D/dalvikvm: Late-enabling CheckJNI
09-27 14:23:34.047 23103-23109/? E/jdwp: Failed sending reply to debugger: Broken pipe
09-27 14:23:34.047 23103-23109/? D/dalvikvm: Debugger has detached; object registry had 1 entries
09-27 14:23:34.197 23103-23103/? D/dalvikvm: GC_FOR_ALLOC freed 2081K, 24% free 19890K/26076K, paused 16ms, total 16ms
09-27 14:23:34.207 23103-23103/? I/dalvikvm-heap: Grow heap (frag case) to 26.631MB for 4192272-byte allocation
09-27 14:23:34.237 23103-23107/? D/dalvikvm: GC_CONCURRENT freed 3K, 21% free 23980K/30172K, paused 3ms+3ms, total 26ms
09-27 14:23:34.257 23103-23103/? D/dalvikvm: GC_FOR_ALLOC freed 2046K, 28% free 21934K/30172K, paused 10ms, total 10ms
09-27 14:23:34.267 23103-23103/? I/dalvikvm-heap: Grow heap (frag case) to 32.628MB for 8386576-byte allocation
09-27 14:23:34.287 23103-23107/? D/dalvikvm: GC_CONCURRENT freed 0K, 22% free 30124K/38364K, paused 5ms+2ms, total 18ms
09-27 14:23:34.297 23103-23103/? D/dalvikvm: GC_FOR_ALLOC freed 4094K, 33% free 26030K/38364K, paused 15ms, total 15ms
09-27 14:23:34.307 23103-23103/? I/dalvikvm-heap: Grow heap (frag case) to 33.850MB for 5473056-byte allocation
09-27 14:23:34.317 23103-23103/? D/dalvikvm: Trying to load lib /data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-0.4.7.so 0x42c3ab98
09-27 14:23:34.317 23103-23103/? D/dalvikvm: Added shared lib /data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-0.4.7.so 0x42c3ab98
09-27 14:23:34.317 23103-23103/? D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-0.4.7.so 0x42c3ab98, skipping init
09-27 14:23:34.317 23103-23103/? D/dalvikvm: Trying to load lib /data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-jni-0.4.7.so 0x42c3ab98
09-27 14:23:34.317 23103-23103/? E/dalvikvm: dlopen("/data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-jni-0.4.7.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1721): could not load library "libmegface-new.so" needed by "libMegviiFacepp-jni-0.4.7.so"; caused by load_library(linker.cpp:771): library "libmegface-new.so" not found
09-27 14:23:34.317 23103-23103/? W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/megvii/facepp/sdk/jni/NativeFaceppAPI;
09-27 14:23:34.317 23103-23103/? D/AndroidRuntime: Shutting down VM
09-27 14:23:34.317 23103-23103/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41ac2ac8)
09-27 14:23:34.327 23103-23103/? E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.ExceptionInInitializerError
at com.megvii.facepp.sdk.Facepp.getSDKAuthType(Facepp.java:294)
at com.megvii.facepp.sdk.Facepp.getApiExpirationMillis(Facepp.java:269)
at com.facepp.demo.LoadingActivity.init(LoadingActivity.java:47)
at com.facepp.demo.LoadingActivity.onCreate(LoadingActivity.java:39)
at android.app.Activity.performCreate(Activity.java:5173)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2262)
at android.app.ActivityThread.access$600(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5145)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:591)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1721): could not load library "libmegface-new.so" needed by "libMegviiFacepp-jni-0.4.7.so"; caused by load_library(linker.cpp:771): library "libmegface-new.so" not found
at java.lang.Runtime.loadLibrary(Runtime.java:371)
at java.lang.System.loadLibrary(System.java:535)
at com.megvii.facepp.sdk.jni.NativeFaceppAPI.(NativeFaceppAPI.java:64)
at com.megvii.facepp.sdk.Facepp.getSDKAuthType(Facepp.java:294) 
at com.megvii.facepp.sdk.Facepp.getApiExpirationMillis(Facepp.java:269) 
at com.facepp.demo.LoadingActivity.init(LoadingActivity.java:47) 
at com.facepp.demo.LoadingActivity.onCreate(LoadingActivity.java:39) 
at android.app.Activity.performCreate(Activity.java:5173) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2262) 
at android.app.ActivityThread.access$600(ActivityThread.java:148) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:5145) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:511) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:591) 
at dalvik.system.NativeStart.main(Native Method) 
09-27 14:23:34.327 23103-23107/? D/dalvikvm: GC_CONCURRENT freed 49K, 19% free 31393K/38364K, paused 6ms+3ms, total 26ms
09-27 14:25:27.708 23103-23103/com.megvii.awesomedemo.facepp E/Parcel: Reading a NULL string not supported here.
09-27 14:25:27.718 23103-23103/? I/Process: Sending signal. PID: 23103 SIG: 9

**Comment by Chaoba** [comment]
不知你是直接引入sdk module还是通过GitPack引入的sdk?在路径MegviiFacepp-Android-SDK/sdk/src/main/jniLibs/arm64-v8a/下我们可以看到libmegface-new.so是存在的。

如果是在Demo上使用GitPack导入依赖的话，请确认是否是在faceppdemoui 这个module里导入依赖的。

**Comment by hloong** [comment]
我是直接git clone下来用as打开的
你们的demo是先引入faceppdemoui这个module，然后faceppdemoui再引入 sdk module，这运行的时候也是这样的，而且我看了，没错jnilibs有这个so，只是demo在手机上一打开就是停止运行，挂掉

**Comment by Chaoba** [comment]
目前的引入代码是这样的
```  
compile 'com.github.FacePlusPlus:MegviiLicMgr-Android-SDK:0.3.0'
//    compile 'com.github.FacePlusPlus:MegviiFacepp-Android-SDK:0.4.7'
compile project(':sdk')
```
你把第二行打开，第三行注释掉再sync一下试试。

**Comment by hloong** [comment]
我刚刚试过了，还是不行，依然挂掉了

**Comment by Chaoba** [comment]
要不你换个手机试试。

**Comment by hloong** [comment]
好吧

**Comment by hloong** [comment]
换了手机还是不行，我在想，你们一运行会自动生成2个jni的so，但是这2个so在我工程里显示的红色错误的，不知道是不是这个问题导致的
09-29 08:37:15.598 1836-1836/com.megvii.awesomedemo.facepp E/dalvikvm: dlopen("/data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-jni-0.4.7.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libmegface-new.so" needed by "libMegviiFacepp-jni-0.4.7.so"; caused by load_library(linker.cpp:745): library "libmegface-new.so" not found
09-29 08:37:15.598 1836-1836/com.megvii.awesomedemo.facepp W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/megvii/facepp/sdk/jni/NativeFaceppAPI;
09-29 08:37:15.598 1836-1836/com.megvii.awesomedemo.facepp D/AndroidRuntime: Shutting down VM
09-29 08:37:15.598 1836-1836/com.megvii.awesomedemo.facepp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x414309a8)
09-29 08:37:15.600 1836-1836/com.megvii.awesomedemo.facepp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libmegface-new.so" needed by "libMegviiFacepp-jni-0.4.7.so"; caused by load_library(linker.cpp:745): library "libmegface-new.so" not found
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                 at java.lang.System.loadLibrary(System.java:514)
                                                                                 at com.megvii.facepp.sdk.jni.NativeFaceppAPI.<clinit>(NativeFaceppAPI.java:64)
                                                                                 at com.megvii.facepp.sdk.Facepp.getSDKAuthType(Facepp.java:294)
                                                                                 at com.megvii.facepp.sdk.Facepp.getApiExpirationMillis(Facepp.java:269)
                                                                                 at com.facepp.demo.LoadingActivity.init(LoadingActivity.java:47)
                                                                                 at com.facepp.demo.LoadingActivity.onCreate(LoadingActivity.java:39)
                                                                                 at android.app.Activity.performCreate(Activity.java:5122)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:156)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:153)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by hloong** [comment]
github抽风了几天，图片传不上来，
其中jniLibs里运行多生成的2个so
libMegviiFacepp-jni-0.4.7.so
libMegviiFaceapp-jni-0.4.7.so
这2个被as标记红色，应该是有问题，我试了2个手机都不行

**Comment by Chaoba** [comment]
libMegviiFaceapp这个名字是不正常的，你全局搜索一下这个字符串看看哪里有？

**Comment by hloong** [comment]
搜了，并没有，但是搜libMegviiFacepp倒是发现了不少

图片我传不上来

在MGFaceppSDK-0.4.7.aar里有

**Comment by jionkang** [comment]
so是从官网下载下来，放到sdk的工程build的aar吗，如果仍然有问题可以尝试下高版本的demo

**Comment by rickythink** [comment]
一样的问题，请问解决了没有呢，完全一样的错误
Android 6.0系统

**Comment by hloong** [comment]
@RickyWong33 没有，没用这个了

**Comment by rickythink** [comment]
@hloong 

sdk模块的`build.gradle`里面的android{}添加
```
packagingOptions {
        pickFirst 'lib/arm64-v8a/libMegviiFacepp-jni-0.4.7.so'
        pickFirst 'lib/armeabi-v7a/libMegviiFacepp-jni-0.4.7.so'
        exclude 'lib/arm64-v8a/libMegviiFacepp-jni-0.4.7.so'
        exclude 'lib/armeabi-v7a/libMegviiFacepp-jni-0.4.7.so'
    }
```

**Comment by jionkang** [comment]
请用新版本，不需要编译aar了
