### ISSUE TITLE
打开录像和区域选择之后大约5s后报错setAudioSource failed

### ISSUE THREAD

**Issue by huangchenggang** [FacePlusPlus/MegviiFacepp-Android-SDK#34]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.megvii.awesomedemo.facepp123, PID: 20340
                  java.lang.RuntimeException: setAudioSource failed.
                      at android.media.MediaRecorder.setAudioSource(Native Method)
                      at com.facepp.library.util.MediaRecorderUtil.prepareVideoRecorder(MediaRecorderUtil.java:46)
                      at com.facepp.library.OpenglActivity.startRecorder(OpenglActivity.java:137)
                      at com.facepp.library.OpenglActivity.access$000(OpenglActivity.java:40)
                      at com.facepp.library.OpenglActivity$1.run(OpenglActivity.java:73)
                      at android.os.Handler.handleCallback(Handler.java:761)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6595)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/Process: Sending signal. PID: 20340 SIG: 9

**Comment by jionkang** [comment]
这个是因为录音权限没有开导致的，demo里没有对录音权限的判断，所以需要自己手动打开。

**Comment by jionkang** [comment]
如果确实需要录像，0.5.2有新版的录像功能，可以录制屏幕的texture
