### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-0.5.2.so" has unexpected e_machine: 40

### ISSUE THREAD

**Issue by ismyaki** [FacePlusPlus/MegviiFacepp-Android-SDK#41]
android 版本4.4.2
專案clone 下來跑就出現以下訊息
不知道官方有沒有文件可以排除

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.megvii.awesomedemo.facepp-1/libMegviiFacepp-0.5.2.so" has unexpected e_machine: 40
    at java.lang.Runtime.loadLibrary(Runtime.java:364)
    at java.lang.System.loadLibrary(System.java:526)
    at com.megvii.facepp.sdk.jni.NativeFaceppAPI.<clinit>(NativeFaceppAPI.java:76)
    at com.megvii.facepp.sdk.Facepp.getSDKAuthType(Facepp.java:350)
    at com.megvii.facepp.sdk.Facepp.getApiExpirationMillis(Facepp.java:325)
    at com.facepp.demo.LoadingActivity.init(LoadingActivity.java:48)
    at com.facepp.demo.LoadingActivity.onCreate(LoadingActivity.java:40)
    at android.app.Activity.performCreate(Activity.java:5411)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
    at android.app.ActivityThread.access$800(ActivityThread.java:139)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:149)
    at android.app.ActivityThread.main(ActivityThread.java:5257)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by jionkang** [comment]
是so的指令集不兼容导致的，第一so有没有做过移动，第二您手机的架构可以描述下吗？

**Comment by jionkang** [comment]
还有模拟器是不兼容的
